// <auto-generated />
namespace DRMS_OCRToolkit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changecoordinatenames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changecoordinatenames));
        
        string IMigrationMetadata.Id
        {
            get { return "202105242049307_change coordinate names"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
